sudo: required

language: ruby
rvm:
  - ruby-2.3.8
  - ruby-2.4.6
  - ruby-2.5.5
  - ruby-2.6.3
  - jruby-9.2.8.0
gemfile:
  - gemfiles/rails_4_2.gemfile
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_5_2.gemfile

matrix:
  include:
    # Ruby 2.7
    # Rails works with Ruby 2.7 only from Rails 5.0
    - rvm: ruby-2.7.0
      gemfile: gemfiles/rails_5_0.gemfile
    - rvm: ruby-2.7.0
      gemfile: gemfiles/rails_5_1.gemfile
    - rvm: ruby-2.7.0
      gemfile: gemfiles/rails_5_2.gemfile

    # Rails 6
    # It requires Ruby 2.5 and above
    - rvm: ruby-2.5.3
      gemfile: gemfiles/rails_6_0.gemfile
    - rvm: ruby-2.6.3
      gemfile: gemfiles/rails_6_0.gemfile
    - rvm: ruby-2.7.0
      gemfile: gemfiles/rails_6_0.gemfile

### BUILD LIFECYCLE STEPS ###

before_install:
  # Debugging: Print out the current docker-compose version.
  - docker-compose --version

  # If one of your containers does not build for
  # whatever reason it's best to report that now before your tests start
  # otherwise it can be really tricky to debug why tests are failing sometimes.
  - docker ps

after_install:
  - gem install bundler -v 1.16.2
  - bundle install

before_script:
  # Start Docker Compose as a daemon
  - docker-compose up -d

script:
  - bundle exec rake spec

after_script:
  - docker-compose down
